Traceback (most recent call last):
  File "/Users/harrison/Desktop/scripting_practice/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
